### ISSUE TITLE
Shouldn't there be a setup.py file?

### ISSUE THREAD

**Issue by DrKat123** [Tymewalk/Tymeventure#1]

**Comment by Tymewalk** [comment]
No, you just run `python3.4 tymeventure.py` to play the game. I'll look into using `setup.py` though - I've never seen it done that way.

**Comment by Tymewalk** [comment]
Done! You can look at [the latest release](https://github.com/Tymewalk/Tymeventure/releases/tag/v0.0.2) which contains a `setup.py` file and the newest version of the game.

Open another issue if there's problems with the `setup.py`. I got it working on my computer.

**Comment by DrKat123** [comment]
Cool!
