### ISSUE TITLE
Plz make a wiki

### ISSUE THREAD

**Issue by DrKat123** [Tymewalk/Tymeventure#2]
Head over to the wiki tab and you know what to do... :P

**Comment by Tymewalk** [comment]
What should I put in the wiki? Should it be like a Wikia for the game or a general development wiki?

**Comment by bjskistad** [comment]
Well, you could have several sections. :D I'm willing to make the wiki. ;)

**Comment by DrKat123** [comment]
@Tymewalk: something like Wikia, but reserve some pages for development wiki :smile:

**Comment by Tymewalk** [comment]
@DrKat123 I think if it's going to be a Wikia I could just put it on Wikia itself (since that has a lot more features), and development wiki could go here.
@bjskistad When this gets sorted out I'll give you a link to wherever it is :smile:

**Comment by DrKat123** [comment]
:roll_out_tongue:

**Comment by DrKat123** [comment]
Whoops :P

**Comment by bjskistad** [comment]
IT'S DRIVING ME NUTSO HAVING NO WIKI!! It's just sitting there. D:

**Comment by DrKat123** [comment]
W00T

**Comment by Tymewalk** [comment]
@DrKat123 @bjskistad I honestly think a wiki for the game would be best on Wikia, and I could link it in README.md. I'll turn off the wiki here for now until I actually use it for development.

**Comment by DrKat123** [comment]
Anyway gonna fork this repo and do some tweakd

**Comment by Tymewalk** [comment]
@DrKat123 Sounds neat! Once you're done make a pull request, I might add it in (and credit you, of course.)

**Comment by Tymewalk** [comment]
There is now a [Tymeventure Wikia](http://tymeventure.wikia.com) that anyone can contribute to.

To recap:

- Tymeventure Wikia is being used as a Wiki for the gameplay
- The Dev Wiki is not needed
- If the Dev Wiki is ever needed, it will be a GitHub Wiki
